"""
Custom asyncpg Record type stubs without Any types.
"""

from typing import Iterator, KeysView, Union, ValuesView

class Record:
    """AsyncPG record with strict typing for field access."""

    def __getitem__(self, key: Union[str, int]) -> object: ...
    def get(self, key: str, default: object = None) -> object: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[object]: ...
    def items(self) -> Iterator[tuple[str, object]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __bool__(self) -> bool: ...
